config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'

  resources :books, only:[:index, :edit, :show, :create, :update, :destroy]
  resources :users, only:[:index, :edit, :show, :create, :update, :destroy]
  get '/home/about' => "homes#about", as: "about"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  # アソシエーション
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy

  has_one_attached :profile_image # モデルに対し、画像を付ける定義付与(ActiveStorage)
  # get_plofile_imageメソッドを作成/画像設定なし→nonimageをデフォルト

  # データが存在しなければならない
  validates :name, uniqueness: true, presence: true, length:{ in: 2..20 ,minimum: 2 } #2-20字
  validates :introduction, length:{ maximum: 50 }# 最大50字

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  # サインアップ後のリダイレクト テスト後
  def after_user_registration_path_for(resource)
    user_path(current_user.id) # 詳細へ
  end

  # サインイン後に転送されるページ(devise用)
  def after_sign_in_path_for(resource)
    user_path(current_user.id) # 詳細へ
  end

  # サインアウト後に転送されるページ(devise用)
  def after_sign_out_path_for(resource)
    root_path
  end

  private
  # nameの入力データを保存(devise用)
   def configure_permitted_parameters
     devise_parameter_sanitizer.permit(:sign_up,keys:[:email])
   end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

# index: books_path = /books
  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
  end

# create: books_path = /books
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id), notice: "You have created book successfully." # 詳細へ
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render :edit
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    @user = @book.user
    if @book.update(book_params)
      redirect_to book_path(@book.id), notice: "You have updated book successfully."
    else
      render :edit
    end
  end

# show: book_path = books/:id
  def show
    #redirect_to books_url if @book.blank? #追記
    @books = Book.all
    @book = Book.find(params[:id])
    @new_book = Book.new
    @user = @book.user
  end

# destroy: book_path  =books/:id
  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

  def correct_user
    @book = Book.find(params[:id])
    @user = @book.user
    redirect_to(books_path) unless @user == current_user
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @books = Book.all
    @book = Book.new
    @users = User.all
    @user = current_user
  end

  def edit
    @user = User.find(params[:id])
    if @user.id == current_user.id
      render :edit
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "You have updated user successfully." #(show)
    else
      #@user = User.find(params[:id])
      render :edit
    end
  end

# show: user_path(user.id) = users/:id
  def show
    @book = Book.new
    @user = User.find(params[:id])
    @books = @user.books
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<!--部分テンプレート-->

<h1>User info</h1>
<div>
  <%= image_tag user.get_profile_image(100,100) %>
</div>
<table class="table">
  <tbody>
     <tr>
       <th>name</th>
       <th><%= user.name %></th>
     </tr>
     <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
     </tr>
  </tbody>
 </table>

 <%= link_to edit_user_path(user.id), class: "btn btn-outline-secondary btn-block" do %>
  <i class="fas fa-user-cog"></i>
 <% end %>

 <h2 class="mt-3">New book</h2>

 <% if @book.errors.any? %>
  <ul class="alert alert-danger" role="alert">
    <h6 class="alert-heading">
     <%= @book.errors.count %>件のエラーが発生しました
    </h6>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
 <% end %>

  <!--New book 投稿機能-->
 <%= form_with model: book do |f| %>
  <p>Title</p>
    <%= f.text_field :title, size: "15", border: "1px solid-gray" %>
  <p>Opinion</p>
    <%= f.text_area :body, size: "18" %>
  <%= f.submit 'Create Book', class:"btn btn-success mt-3" %>
 <% end %>

app/views/books/edit.html.erb
<!--edit_book_path(/books/:id/edit)-->
<div class="container">
  <div class="row">
    <div class="col-md-8 px-5 px-sm-0 mx-auto">
      <h1 class="top-heading mt-2">Editing Book</h1>

       <% if @book.errors.any? %>
         <ul class="alert alert-danger" role="alert">
          <h6 class="alert-heading">
           <%= @book.errors.count %> error prohibited this obj from being saved:
          </h6>
           <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
           <% end %>
         </ul>
       <% end %>

        <%= form_with model: @book, url: book_path(@book.id), method: :patch do |f| %>
         <label for="inputTitle">Title</label>
          <p><%= f.text_field :title, id:"inputName", size: "50", border: "1px solid-#ced4da" %></p>
         <label for="inputBody">Opinion</label>
          <p><%= f.text_field :body, id:"inputBody", size: "50", border: "1px solid-#ced4da" %></p>
          <%= f.submit "Update Book", class: "btn btn-success mt-3" %>
        <% end %>
     <p class="link p-2">
      <%= link_to 'Show', book_path(@book.id) %> |
      <%= link_to 'Back', books_path %>
     </p>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container">
 <div class="row">
  <div class="col-md-3">
   <%= render 'list',user: @user, book: @book %>
  </div>

<!--books_path(/books)-->
  <div class="col-md-8 offset-md-1">
   <h2>Books</h2>
     <table class="table table-hover table-inverse">
       <thead>
        <tr>
         <th>Title</th>
         <th>Opinion</th>
        </tr>
       </thead>
     <tbody>
     <% @books.each do |book| %>
       <tr>
         <td>
         <%= link_to user_path(book.user.id) do %>
          <%= image_tag(book.user.profile_image, size:"80") %>
         <% end %>
         </td>
         <td><%= link_to book.title, book_path(book.id) %></td>
         <td><%= book.body %></td>
       </tr>
   <% end %>
     </tbody>
   </table>
  </div>
 </div>
</div>

app/views/books/show.html.erb
<!--New book 投稿機能-->
<div class="container">
 <div class="row">
  <div class="col-md-3">
    <%= render 'list',user: @user, book: @new_book %>
  </div>
<!--Books詳細-->
  <div class="col-md-8 offset-md-1">
   <h2 class="top-header mt-3">Book detail</h2>
    <table class="table">
      <tbody>
        <tr>
          <td>
            <%= image_tag @user.get_profile_image(100,100) %><br>
            <%= link_to user_path(@user.id) do %>
              <%= @user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, book_path(@book.id) %> </td>
          <td><%= @book.body %></td>
          <% if @user.id == current_user.id %>
          <td><%= link_to "Edit", edit_book_path(@book.id), class: "btn btn-sm btn-success" %></td>
          <% end %>
          <% if @user.id == current_user.id %>
          <td><%= link_to 'Destroy',book_path(@book.id), method: :delete, "data-confirm" => "本当に削除しますか？" ,class: "btn btn-sm btn-danger"%></td>
          <% end %>
        </tr>
       </tbody>
    </table>
   </div>
  </div>
 </div>
</div>

app/views/homes/about.html.erb
<main>
  <div class="container">
   <div class="row">
    <div class="mx-auto">
     <h1>
      <p>welcome to<i class="fas fa-book"></i><strong>Bookers!</strong></p>
     </h1>
    </div>
   </div>
  </div>
</main>

app/views/homes/top.html.erb
<main>
 <div class="container">
  <div class="row">
   <div class="mx-auto">
    <h1>
     <span>welcome to<i class="fas fa-book"></i><strong>Bookers</strong> !!</span>
    </h1>
    <p>In<i class="fas fa-book"></i><strong>Bookers</strong>,</p>
    <p>you can share and exchange your opinions,inpressions,and emotions</p>
    <p>about various books!</p>
    
<!--リンク-->
     <% if user_signed_in? %>
<!--以下二行リンク Userページに変更する-->
     <div class="btn-wrapper col-10 mx-auto">
        <p><%= link_to "log in", about_path, class: "btn btn-info btn-sm btn-block md-3" %></p>
        <p><%= link_to "sign up", about_path, class: "btn btn-success btn-sm btn-block md-3" %></p>
     <% else %>
        <p><%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-sm btn-block md-3" %></p>
        <p><%= link_to "Sign up", new_user_registration_path, class:"btn btn-success btn-sm btn-block md-3" %></p>
     <% end %>
     </div>
    </div>
   </div>
  </div>
 </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <!--fontawesome-->
    <script src="https://kit.fontawesome.com/1f14f03d82.js" crossorigin="anonymous"></script>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-bland" href="/"><span class="navbar-brand md-0 h1 text-white">Bookers</span></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
             <li class="nav-item">
               <%= link_to user_path(current_user.id), class: "nav-link text-light" do %>
                <i class="fas fa-home"></i>
                Home
               <% end %>
             </li>
             <li class="nav-item">
               <%= link_to users_path, class: "nav-link text-light" do %>
                <i class="fas fa-users"></i>
                Users
               <% end %>
             </li>
             <li class="nav-item">
               <%= link_to books_path, class: "nav-link text-light" do %>
                <i class="fas fa-book-open"></i>
                Books
               <% end %>
             </li>
             <li class="nav-item">
               <%= link_to destroy_user_session_path, method: :delete, class: "nav-link text-light" do %>
                <i class="fas fa-sign-out-alt"></i>
                Log out
               <% end %>
             </li>
            <% else %>
             <li class="nav-item">
               <%= link_to root_path, class: "nav-link text-light" do %>
                <i class="fas fa-home"></i>
                Home
               <% end %>
             </li>
             <li class="nav-item">
               <%= link_to about_path, class: "nav-link text-light" do %>
                <i class="fas fa-link"></i>
                About
               <% end %>
             </li>
             <li class="nav-item">
               <%= link_to new_user_registration_path, class: "nav-link text-light" do %>
                <i class="fas fa-user-plus"></i>
                Sign up
               <% end %>
             </li>
              <li class="nav-item">
               <%= link_to new_user_session_path, class: "nav-link text-light" do %>
                <i class="fas fa-sign-in-alt"></i>
                Log in
               <% end %>
             </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <main>
      <% if flash[:notice] %>
       <p id = "notice"><%= flash[:notice] %></p>
      <% end %>
    <%= yield %>
    </main>

    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>


  </body>
</html>

app/views/users/edit.html.erb
<p id="notice"></p>

<div class="container">
  <div class="row">
    <div class="col-md-8 px-5 mx-auto">
      <h2>User info</h2>

        <% if @user.errors.any? %>
          <ul class="alert alert-danger" role="alert">
            <h6 class="alert-heading">
              <%= @user.errors.count %>件のエラーが発生しました
            </h6>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>

        <%= form_with model: @user, url: user_path(@user.id), method: :patch do |f| %>
         <label for="inputName">Name</label>
          <p><%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前", size: "30", border: "1px solid-#ced4da" %></p>
         <label for="inputImage">ProfileImage</label>
          <p><%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %></p>
         <label for="inputIntroduction">Introduction</label>
          <p><%= f.text_field :introduction, autofocus: true, id:"inputintroduction", placeholder:"自己紹介", size: "30", border: "1px solid-#ced4da" %></p>
          <%= f.submit "Update User", class: "btn btn-secondary mt-3" %>
        <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<!--users_path(/users)-->
<!--New book 投稿機能-->
<div class="container px-5 px-sm-0">
 <div class="row">
  <div class="col-md-3">
   <%= render 'books/list',user: @user, book: @book %>
  </div>
  <div class="col-md-8 offset-md-1">
   <h2>Users</h2>
   <table class="table">
     <thead>
       <tr>
        <th>image</th>
        <th>name</th>
        <th colspan="3"></th>
       </tr>
     </thead>
     <tbody>
       <% @users.each do |users| %>
       <tr>
        <td><%= image_tag users.profile_image, size:"80" %></td>
        <td><%= users.name %></td>
        <td><%= link_to "Show", user_path(users.id) %></td>
       </tr>
       <% end %>
     </tbody>
    </table>
  </div>
 </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render '/books/list',user: @user, book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
<!--Books一覧 Home-->
     <h3 class="top-heading mt-1">Books</h3>
     <table class="table">
      <thead>
       <tr>
        <th>Title</th>
        <th>Opinion</th>
       </tr>
      </thead>
      <tbody>
      <% @books.each do |books| %>
       <tr>
        <td>
         <%= link_to user_path(books.user_id) do %>
          <%= image_tag books.user.get_profile_image(100,100) %>
         <% end %>
        </td>
        <td><%= link_to books.title, book_path(books.id) %></td>
        <td><%= books.body %></td>
       </tr>
      <% end %>
      </tbody>
     </table>
   </div>
  </div>
</div>